#!/usr/bin/env python3
"""Merge deploy/env.production.example + deploy/secrets.env → deploy/.env

Edit ONE file for passwords/tokens: deploy/secrets.env (gitignored).
Committed defaults: deploy/env.production.example

  python3 scripts/render_deploy_env.py              # write deploy/.env
  python3 scripts/render_deploy_env.py --dry-run    # print to stdout
  python3 scripts/render_deploy_env.py --check      # verify required keys non-empty (after write)

See deploy/README-SECRETS.md
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_DEFAULT_BASE = _REPO / "deploy" / "env.production.example"
_DEFAULT_SECRETS = _REPO / "deploy" / "secrets.env"
_DEFAULT_OUT = _REPO / "deploy" / ".env"

# Keys that must be non-empty for a typical production droplet (soft check).
_REQUIRED_DEFAULT = (
    "DATABASE_URL",
    "REDIS_URL",
    "CELERY_BROKER_URL",
    "CELERY_RESULT_BACKEND",
    "PUBLIC_API_URL",
)

_KEY_LINE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)\s*$")


def _parse_env_from_lines(lines: list[str]) -> dict[str, str]:
    out: dict[str, str] = {}
    for line in lines:
        raw = line.strip()
        if not raw or raw.startswith("#"):
            continue
        if "=" not in raw:
            continue
        k, _, v = raw.partition("=")
        k = k.strip()
        v = v.strip()
        if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
            v = v[1:-1]
        out[k] = v
    return out


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    return _parse_env_from_lines(path.read_text(encoding="utf-8").splitlines())


def _fmt_val(v: str) -> str:
    if not v:
        return ""
    if any(ch in v for ch in ' \n\r\t#"' "'" "="):
        esc = v.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{esc}"'
    return v


def render(base_path: Path, secrets_path: Path) -> str:
    """Merge: secrets override base. Preserve base file line order and comments."""
    secrets = _parse_env_file(secrets_path)
    merged: dict[str, str] = {**_parse_env_file(base_path), **secrets}

    lines_out: list[str] = []
    lines_out.append("# Generated by scripts/render_deploy_env.py — do not edit deploy/.env by hand.")
    lines_out.append("# Edit deploy/secrets.env then run: python3 scripts/render_deploy_env.py")

    def _rel(p: Path) -> str:
        try:
            return str(p.resolve().relative_to(_REPO))
        except ValueError:
            return str(p.resolve())

    lines_out.append(f"# Base: {_rel(base_path)} | Secrets: {_rel(secrets_path)}")
    lines_out.append("")

    seen: set[str] = set()
    for line in base_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped:
            lines_out.append("")
            continue
        if stripped.startswith("#"):
            lines_out.append(line)
            continue
        m = _KEY_LINE.match(line.rstrip("\n"))
        if m:
            k = m.group(1)
            if k in merged:
                lines_out.append(f"{k}={_fmt_val(merged[k])}")
                seen.add(k)
            else:
                lines_out.append(line.rstrip("\n"))
            continue
        lines_out.append(line.rstrip("\n"))

    only_secrets = sorted(k for k in merged if k not in seen)
    if only_secrets:
        lines_out.append("")
        lines_out.append("# --- keys only in deploy/secrets.env ---")
        for k in only_secrets:
            lines_out.append(f"{k}={_fmt_val(merged[k])}")

    return "\n".join(lines_out) + "\n"


def check_output(env_text: str) -> list[str]:
    data = _parse_env_from_lines(env_text.splitlines())
    problems: list[str] = []
    for k in _REQUIRED_DEFAULT:
        v = (data.get(k) or "").strip()
        if not v or "YOUR_" in v or "changeme" in v.lower() or "PASTE_" in v:
            problems.append(f"missing or placeholder: {k}")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description="Merge deploy/env.production.example + deploy/secrets.env → deploy/.env")
    ap.add_argument("--base", type=Path, default=_DEFAULT_BASE, help="Committed template")
    ap.add_argument("--secrets", type=Path, default=_DEFAULT_SECRETS, help="Gitignored overrides")
    ap.add_argument("--out", type=Path, default=_DEFAULT_OUT, help="Output path")
    ap.add_argument("--dry-run", action="store_true", help="Print merged env to stdout; do not write")
    ap.add_argument("--check", action="store_true", help="After write, verify required keys")
    args = ap.parse_args()

    if not args.base.is_file():
        print(f"error: base file not found: {args.base}", file=sys.stderr)
        return 2

    if not args.secrets.is_file():
        print(
            f"note: {args.secrets} missing — output uses base only. Copy deploy/secrets.env.example → secrets.env",
            file=sys.stderr,
        )

    text = render(args.base, args.secrets)

    if args.dry_run:
        sys.stdout.write(text)
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"Wrote {args.out} ({len(text)} bytes)")

    probs = check_output(text)
    if probs:
        print("Warnings:", file=sys.stderr)
        for p in probs:
            print(f"  - {p}", file=sys.stderr)
        if args.check:
            return 2
    elif args.check:
        print("Required keys look non-empty.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())